#!/usr/bin/env bash
#
# Build a PRODUCTION extension into dist/ and a zip for the Chrome Web Store.
#
# It bakes the relay URL from .env (SERVER_URL=...) into the build and locks it,
# which makes the popup hide the "Server URL" field — end users can't (and don't
# need to) change it. The source tree in extension/ stays in dev mode.
#
#   ./build-prod.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$ROOT/extension"
DIST="$ROOT/dist"
ENV_FILE="$ROOT/.env"

# --- read SERVER_URL from .env ---
if [ ! -f "$ENV_FILE" ]; then
  echo "✗ .env not found. Copy .env.example to .env and set SERVER_URL." >&2
  exit 1
fi
SERVER_URL="$(grep -E '^[[:space:]]*SERVER_URL[[:space:]]*=' "$ENV_FILE" | tail -1 | cut -d= -f2- | sed -E 's/^[[:space:]]*//; s/[[:space:]]*$//; s/^"//; s/"$//')"
if [ -z "${SERVER_URL:-}" ]; then
  echo "✗ SERVER_URL is empty in .env" >&2
  exit 1
fi
case "$SERVER_URL" in
  ws://*|wss://*) ;;
  *) echo "✗ SERVER_URL must start with ws:// or wss:// (got: $SERVER_URL)" >&2; exit 1 ;;
esac

echo "• Production relay: $SERVER_URL"

# --- assemble dist/ ---
rm -rf "$DIST"
mkdir -p "$DIST"
cp -R "$SRC/." "$DIST/"
# strip dev-only files from the build
find "$DIST" -name '*.test.js' -delete
rm -f "$DIST/icons/icon.svg"

# --- bake the locked relay into the config the extension reads ---
cat > "$DIST/shared/config.js" <<EOF
// GENERATED by build-prod.sh — do not edit. Locks the relay and hides the
// Server URL field in the UI.
(function (root) {
  root.WP = root.WP || {};
  root.WP.config = {
    lockedServerUrl: '$SERVER_URL',
  };
})(typeof window !== 'undefined' ? window : globalThis);
EOF

# --- zip for the Web Store (manifest.json at the zip root) ---
VERSION="$(node -e "process.stdout.write(require('$DIST/manifest.json').version)")"
OUT="$ROOT/pawp-connect-prod-v${VERSION}.zip"
rm -f "$OUT"
( cd "$DIST" && zip -r "$OUT" . -x '*/.DS_Store' -x '.DS_Store' >/dev/null )

echo "✓ Built dist/  and  $(basename "$OUT")"
echo "  Load unpacked:  $DIST"
echo "  Upload to store: $OUT"
echo "  Server URL field is hidden; relay is locked to $SERVER_URL"
